<?php
$config= [
			'add_article_rules'=>array(
											array(
													'field'=>'title',
													'label'=>'Title',
													'rules'=>'required'
												),
											array(
													'field'=>'article',
													'label'=>'Article',
													'rules'=>'required'
												)
										),
			'edit_article_rules'=>array(
											array(
													'field'=>'title',
													'label'=>'Title',
													'rules'=>'required'
												),
											array(
													'field'=>'article',
													'label'=>'Article',
													'rules'=>'required'
												)
										)
				
		  ];
?>